{{- if and (.Values.stargate.enabled) (.Values.cassandra.enabled) }}
  {{- $stargateVersion := .Values.stargate.version }}
  {{- $computedClusterVersion := "" }}
  {{- $computedImage := "" }}
  {{- if hasPrefix "3" .Values.cassandra.version }}
    {{- $computedClusterVersion = "3.11" }}
    {{- $computedImage = printf "stargateio/stargate-3_11:v%s" $stargateVersion }}
  {{- else }}
    {{- $computedClusterVersion = "4.0" }}
    {{- $computedImage = printf "stargateio/stargate-4_0:v%s" $stargateVersion }}
  {{- end }}
  {{- $image := default $computedImage .Values.stargate.image -}}
  {{- $clusterVersion := default $computedClusterVersion .Values.stargate.clusterVersion -}}
  {{- $heapMB := required "stargate.heapMB is required" .Values.stargate.heapMB -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ include "k8ssandra.datacenterName" . }}-stargate
  labels:
    release: {{ .Release.Name }}
    app: {{ .Release.Name }}-{{ include "k8ssandra.datacenterName" . }}-stargate
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  replicas: {{ required "stargate.replicas is required" .Values.stargate.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ include "k8ssandra.datacenterName" . }}-stargate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ include "k8ssandra.datacenterName" . }}-stargate
    spec:
      initContainers:
          - name: wait-for-cassandra
            image: alpine:3.12.2
            imagePullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - |
                echo "Waiting for all Cassandra nodes in {{ include "k8ssandra.datacenterName" . }} to finish bootstrapping..."
                while [ "$(nslookup {{ include "k8ssandra.clusterName" . }}-{{ include "k8ssandra.datacenterName" . }}-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }} | grep Name | wc -l)" != "{{ include "k8ssandra.datacenterSize" . }}" ]; do
                    sleep 5
                done
                echo "Cassandra is ready. Starting Stargate..."
          {{- if and (.Values.reaper.enabled) }}
          - name: wait-for-reaper
            image: curlimages/curl:7.77.0
            imagePullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - |
                echo "Waiting for the Reaper pod in {{ include "k8ssandra.datacenterName" . }} to finish starting..."
                curl http://{{ include "k8ssandra.clusterName" . }}-reaper-reaper-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }}:8080/cluster --fail
                while [ $? -ne 0 ]; do
                    sleep 5
                    curl http://{{ include "k8ssandra.clusterName" . }}-reaper-reaper-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }}:8080/cluster --fail
                done
                echo "Reaper is ready. Starting Stargate..."
          {{- end }}
      containers:
        - name: {{ .Release.Name }}-{{ include "k8ssandra.datacenterName" . }}-stargate
          image: {{ $image }}
          imagePullPolicy: {{ .Values.stargate.imagePullPolicy }}
          ports:
            - name: graphql
              containerPort: 8080
              protocol: TCP
            - name: authorization
              containerPort: 8081
              protocol: TCP
            - name: rest
              containerPort: 8082
              protocol: TCP
            - name: health
              containerPort: 8084
              protocol: TCP
            - name: metrics
              containerPort: 8085
              protocol: TCP
            - name: http-schemaless
              containerPort: 8090
              protocol: TCP
            - name: native
              containerPort: 9042
              protocol: TCP
            - name: inter-node-msg
              containerPort: 8609
              protocol: TCP
            - name: intra-node
              containerPort: 7000
              protocol: TCP
            - name: tls-intra-node
              containerPort: 7001
              protocol: TCP
          resources:
            limits:
              cpu: {{ required "stargate.cpuLimMillicores is required" .Values.stargate.cpuLimMillicores }}m
              memory: {{ mul 4 $heapMB }}Mi
            requests:
              cpu: {{ required "stargate.cpuReqMillicores" .Values.stargate.cpuReqMillicores }}m
              memory: {{ mul 2 $heapMB }}Mi
          env:
            - name: JAVA_OPTS
              value: >-
                -XX:+CrashOnOutOfMemoryError
                -Xms{{ $heapMB }}M
                -Xmx{{ $heapMB }}M
            - name: CLUSTER_NAME
              value: {{ include "k8ssandra.clusterName" . | quote }}
            - name: CLUSTER_VERSION
              value: {{ $clusterVersion | quote }}
            - name: SEED
              value: "{{ include "k8ssandra.clusterName" . }}-seed-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain | default "cluster.local" }}"
            - name: DATACENTER_NAME
              value: {{ include "k8ssandra.datacenterName" . }}
            - name: RACK_NAME
              # The rack name is temporarily hard coded until we get multi-rack support implemented.
              # See https://github.com/k8ssandra/k8ssandra/issues/54.
              value: default
            - name: ENABLE_AUTH
              value: "true"
          livenessProbe:
            httpGet:
              path: /checker/liveness
              port: health
            timeoutSeconds: 20
            initialDelaySeconds: {{ .Values.stargate.livenessInitialDelaySeconds }}
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /checker/readiness
              port: health
            timeoutSeconds: 20
            initialDelaySeconds: {{ .Values.stargate.readinessInitialDelaySeconds }}
            failureThreshold: 20
      {{- if .Values.stargate.tolerations }}
      tolerations: {{ toYaml .Values.stargate.tolerations | nindent 6 }}
      {{- end }}
{{- end }}
