---
on:
  push:
    branches:
      - test

jobs:
  integration-tests-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker
        run: |
          brew install docker
          brew install virtualbox --cask
          brew install docker-machine
          docker-machine create --driver virtualbox default

      - name: Install Dependencies
        run: |
          set -x
          brew update

          # install Go
          brew install go
          export PATH=$PATH:/usr/local/go/bin
          go version

          # install kubectl
          brew install kubectl 

          # install kind
          brew install kind

          # install Helm 
          brew install helm || brew upgrade helm

          # install jq
          brew install jq

          # install godog
          go get github.com/cucumber/godog/cmd/godog@v0.11.0

      - name: Run Integration Tests
        run: |
          cd tests/integration
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH:$GOPATH/bin
          godog
